stages:
  - name: buildTTGateway
    transformations:
      - checkout
      - compile
      - rto-dist
      - rto-optimize-failedtests-selection

transformations:
  - name: checkout
    service: git-service
    command: checkout
    parameters:
      repositoryUri: https://github.com/sungkangaw/rto-example-triangletester.git

  - name: compile
    service: maven-service
    command: compile
    dependsOn:
      - alias: repo
        ref: p://this/transformations/checkout/workspace
    parameters:
      workspace: "@repo"

  - name: rto-dist
    service: rto-test-service
    command: discover
    dependsOn:
      - alias: compile
        ref: p://this/transformations/compile/classes
    parameters:
      classes: "@compile"

  - name: rto-optimize-failedtests-selection
    service: rto-optimize-failedtestsselection-service
    command: optimize
    dependsOn:
      - alias: testclasses
        ref: p://this/transformations/rto-dist/testClasses
    parameters:
      testRef: "@testclasses"     

assessments:
  - name: rto-run
    service: rto-test-service
    command: execute
    dependsOn:
      - alias: compile
        ref: p://this/transformations/compile/classes
      - alias: testclasses
        ref: p://this/transformations/rto-optimize-failedtests-selection/testRef
    parameters:
      classes: "@compile"
      testOrder: "@testclasses"
      
probes:
  - name: rto-probe
    service: rto-test-history-probe-service
    command: probe
    dependsOn:
      - alias: testreport
        ref: p://this/assessments/rto-run/testReport
    parameters:
      testReport: "@testreport"
 
qualityGates: 
  - strategy: auto
    policies:
      - name: PassedTestRate
        interpretation: threshold-
        actualValue: passedRate
        setPoint: 0.5
        assessmentRef: p://this/assessments/rto-run
